# config.yaml
version: 1.0.0

hyperparameters:
  num_epochs: 5
  learning_rate: 1e-5

dataloader:
  batch_size: 2

models:
  - AlBERT
  - BERT
  - CamemBERT
  - DistilBERT
  - RetriBERT
  - MobileBERT
  - PhoBERT
  - RoBERTa
  - XLMNet

data:
  file_path: /home/tomato/Downloads/data.csv
